"""empty message

Revision ID: 22910722322f
Revises: 5f6d5df3dff1
Create Date: 2025-04-07 21:13:10.858928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22910722322f'
down_revision: Union[str, None] = '5f6d5df3dff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'containers', ['container_id', 'network_id'])
    op.create_unique_constraint(None, 'networks', ['network_id', 'host_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'networks', type_='unique')
    op.drop_constraint(None, 'containers', type_='unique')
    # ### end Alembic commands ###
