"""empty message

Revision ID: 461c3cd42fef
Revises: 0ab321870cd3
Create Date: 2025-04-05 19:45:13.234159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '461c3cd42fef'
down_revision: Union[str, None] = '0ab321870cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('container_links', sa.Column('network_id', sa.Integer(), nullable=False))
    op.drop_constraint('container_links_parent_id_fkey', 'container_links', type_='foreignkey')
    op.create_foreign_key(None, 'container_links', 'networks', ['network_id'], ['id'])
    op.drop_column('container_links', 'parent_id')
    op.add_column('containers', sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('hosts', sa.Column('agent_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'agent_id')
    op.drop_column('containers', 'ip')
    op.add_column('container_links', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'container_links', type_='foreignkey')
    op.create_foreign_key('container_links_parent_id_fkey', 'container_links', 'containers', ['parent_id'], ['id'])
    op.drop_column('container_links', 'network_id')
    op.drop_table('networks')
    # ### end Alembic commands ###
