"""empty message

Revision ID: 5f6d5df3dff1
Revises: bb26fc95b850
Create Date: 2025-04-07 21:11:21.400326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f6d5df3dff1'
down_revision: Union[str, None] = 'bb26fc95b850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_host',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'host_id')
    )
    op.create_table('network_to_network',
    sa.Column('source_network_id', sa.Integer(), nullable=False),
    sa.Column('target_network_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['target_network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('source_network_id', 'target_network_id')
    )
    op.drop_table('network_hosts')
    op.drop_table('container_network')
    op.add_column('containers', sa.Column('network_id', sa.Integer(), nullable=False))
    op.drop_constraint('containers_host_id_fkey', 'containers', type_='foreignkey')
    op.create_foreign_key(None, 'containers', 'networks', ['network_id'], ['id'])
    op.drop_column('containers', 'host_id')
    op.drop_constraint('hosts_cluster_id_fkey', 'hosts', type_='foreignkey')
    op.drop_column('hosts', 'cluster_id')
    op.add_column('networks', sa.Column('host_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'networks', 'hosts', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'networks', type_='foreignkey')
    op.drop_column('networks', 'host_id')
    op.add_column('hosts', sa.Column('cluster_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('hosts_cluster_id_fkey', 'hosts', 'clusters', ['cluster_id'], ['id'])
    op.add_column('containers', sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.create_foreign_key('containers_host_id_fkey', 'containers', 'hosts', ['host_id'], ['id'])
    op.drop_column('containers', 'network_id')
    op.create_table('container_network',
    sa.Column('network_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name='container_network_container_id_fkey'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name='container_network_network_id_fkey'),
    sa.PrimaryKeyConstraint('network_id', 'container_id', name='container_network_pkey'),
    sa.UniqueConstraint('network_id', 'container_id', name='container_network_network_id_container_id_key')
    )
    op.create_table('network_hosts',
    sa.Column('network_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name='network_hosts_host_id_fkey'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name='network_hosts_network_id_fkey'),
    sa.PrimaryKeyConstraint('network_id', 'host_id', name='network_hosts_pkey')
    )
    op.drop_table('network_to_network')
    op.drop_table('cluster_host')
    # ### end Alembic commands ###
