"""empty message

Revision ID: 640e86fa8a60
Revises: 76c73bd1fa29
Create Date: 2025-04-07 13:34:24.778734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '640e86fa8a60'
down_revision: Union[str, None] = '76c73bd1fa29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'container_network', ['network_id', 'container_id'])
    op.add_column('containers', sa.Column('last_active', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'last_active')
    op.drop_constraint(None, 'container_network', type_='unique')
    # ### end Alembic commands ###
