"""empty message

Revision ID: 9516cb098c3f
Revises: 2cade05c8ca7
Create Date: 2025-04-05 20:49:56.161820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9516cb098c3f'
down_revision: Union[str, None] = '2cade05c8ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'container_network', ['network_id', 'container_id'])
    op.drop_column('container_network', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_network', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'container_network', type_='unique')
    # ### end Alembic commands ###
