"""empty message

Revision ID: a5d0d20d70e0
Revises: 461c3cd42fef
Create Date: 2025-04-05 19:47:15.424912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5d0d20d70e0'
down_revision: Union[str, None] = '461c3cd42fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('container_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('container_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('network_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name='container_links_container_id_fkey'),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], name='container_links_network_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='container_links_pkey')
    )
    op.drop_table('container_network')
    # ### end Alembic commands ###
