"""empty message

Revision ID: bb26fc95b850
Revises: 640e86fa8a60
Create Date: 2025-04-07 18:01:59.231197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb26fc95b850'
down_revision: Union[str, None] = '640e86fa8a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hosts', sa.Column('cluster_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hosts', 'clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hosts', type_='foreignkey')
    op.drop_column('hosts', 'cluster_id')
    op.drop_table('clusters')
    # ### end Alembic commands ###
