"""empty message

Revision ID: eaff08a3c3cd
Revises: 9516cb098c3f
Create Date: 2025-04-06 13:39:40.100701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eaff08a3c3cd'
down_revision: Union[str, None] = '9516cb098c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('networks', sa.Column('network_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'network_id')
    op.drop_column('hosts', 'token')
    # ### end Alembic commands ###
