name: Deploy

on:
  # Allow manual trigger of the workflow
  workflow_dispatch:
  # Verify build on any push; deploy only on master branch
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true # Stop script on error
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/Asirius-API
            git pull origin master
            docker compose up -d --build --pull always